db:
  image: "postgres:11.5"
  volumes: 
    - ./db/create_users.sql:/docker-entrypoint-initdb.d/10-init.sql
    - ./db/data:/var/lib/postgresql/data:z
  environment:
    - POSTGRES_USER=pgobserve
    - POSTGRES_PASSWORD=pgobserve
  ports:
    - "5432:5432"
api:
  build: .
  ports:
    - "5000:5000"
  links:
    - "db"
  environment:
    - DATABASE_HOST=db
    - DATABASE_NAME=pgobserve
    - DATABASE_USER=pgobserve
    - DATABASE_PASSWORD=pgobserve
  command:
    ["./wait-for-it.sh", "db:5432", "--", "python",  "app.py"]
